apiVersion: v1
kind: Service
metadata:
  name: nexus-service
  namespace: devops
spec:
  selector:
    app: nexus
  ports:
    - name: nexus-http
      protocol: TCP
      port: 8081
      targetPort: 8081
    - name: nexus-docker
      protocol: TCP
      port: 8082
      targetPort: 8082
    - name: nexus-helm
      protocol: TCP
      port: 8083
      targetPort: 8083
