apiVersion: "v1"
kind: "PersistentVolumeClaim"
metadata:
  name: nexus-volume-claim
  namespace: devops
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
  storageClassName: longhorn
