apiVersion: "v1"
kind: "PersistentVolumeClaim"
metadata:
  name: nexus-volume-claim2
  namespace: devops
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
